version: '3'
services:
  sdcccompiler:
    image: 139.9.186.120:8080/sdcc_compiler:latest
    container_name: sdcc-compiler
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./workdir:/root/workdir
